//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/NewInput/InputActions 1.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions1 : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions1()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions 1"",
    ""maps"": [
        {
            ""name"": ""HandyDandy"",
            ""id"": ""67d59547-fac1-4c0a-b46c-634a9fb3a248"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""0ced3a76-45fd-4b0b-ab9f-8a8aa1436dbb"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f0e71ba2-bb1b-470d-9469-fa83f65c4df7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpRelease"",
                    ""type"": ""Button"",
                    ""id"": ""f1f8e232-c3df-4e1a-bc48-729beed45d8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Emote"",
                    ""type"": ""Button"",
                    ""id"": ""256d4c61-d118-4d28-a05f-dd94fc16a3d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EmoteRelease"",
                    ""type"": ""Button"",
                    ""id"": ""bc44d210-9fb5-4179-90f2-3f78083d9f63"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""44c06aa5-c9f4-4591-a54c-0fe8a6d03fba"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""D-Pad"",
                    ""id"": ""85026f8f-2941-4089-a01e-5fa8e5a87a6c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f3ae572b-1f61-44a6-8c57-5a8dfae7f0b2"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7acaca76-a91f-416f-b4f6-6bddc38793bd"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ecd4366a-290e-45de-9781-c678f98d43a7"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f1bdde3d-2090-4923-86be-f59b294d01f2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""df32f4c5-f425-4e84-ac3e-09743b0236c8"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e12ef44-e58d-4c57-a596-04a978e3b6ef"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5db69130-b097-4c0f-851c-f4de619a701f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Emote"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a37ff77e-73cc-4287-8e89-47363e3638dd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EmoteRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // HandyDandy
        m_HandyDandy = asset.FindActionMap("HandyDandy", throwIfNotFound: true);
        m_HandyDandy_Move = m_HandyDandy.FindAction("Move", throwIfNotFound: true);
        m_HandyDandy_Jump = m_HandyDandy.FindAction("Jump", throwIfNotFound: true);
        m_HandyDandy_JumpRelease = m_HandyDandy.FindAction("JumpRelease", throwIfNotFound: true);
        m_HandyDandy_Emote = m_HandyDandy.FindAction("Emote", throwIfNotFound: true);
        m_HandyDandy_EmoteRelease = m_HandyDandy.FindAction("EmoteRelease", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HandyDandy
    private readonly InputActionMap m_HandyDandy;
    private IHandyDandyActions m_HandyDandyActionsCallbackInterface;
    private readonly InputAction m_HandyDandy_Move;
    private readonly InputAction m_HandyDandy_Jump;
    private readonly InputAction m_HandyDandy_JumpRelease;
    private readonly InputAction m_HandyDandy_Emote;
    private readonly InputAction m_HandyDandy_EmoteRelease;
    public struct HandyDandyActions
    {
        private @InputActions1 m_Wrapper;
        public HandyDandyActions(@InputActions1 wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_HandyDandy_Move;
        public InputAction @Jump => m_Wrapper.m_HandyDandy_Jump;
        public InputAction @JumpRelease => m_Wrapper.m_HandyDandy_JumpRelease;
        public InputAction @Emote => m_Wrapper.m_HandyDandy_Emote;
        public InputAction @EmoteRelease => m_Wrapper.m_HandyDandy_EmoteRelease;
        public InputActionMap Get() { return m_Wrapper.m_HandyDandy; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HandyDandyActions set) { return set.Get(); }
        public void SetCallbacks(IHandyDandyActions instance)
        {
            if (m_Wrapper.m_HandyDandyActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnJump;
                @JumpRelease.started -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnJumpRelease;
                @JumpRelease.performed -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnJumpRelease;
                @JumpRelease.canceled -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnJumpRelease;
                @Emote.started -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnEmote;
                @Emote.performed -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnEmote;
                @Emote.canceled -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnEmote;
                @EmoteRelease.started -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnEmoteRelease;
                @EmoteRelease.performed -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnEmoteRelease;
                @EmoteRelease.canceled -= m_Wrapper.m_HandyDandyActionsCallbackInterface.OnEmoteRelease;
            }
            m_Wrapper.m_HandyDandyActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @JumpRelease.started += instance.OnJumpRelease;
                @JumpRelease.performed += instance.OnJumpRelease;
                @JumpRelease.canceled += instance.OnJumpRelease;
                @Emote.started += instance.OnEmote;
                @Emote.performed += instance.OnEmote;
                @Emote.canceled += instance.OnEmote;
                @EmoteRelease.started += instance.OnEmoteRelease;
                @EmoteRelease.performed += instance.OnEmoteRelease;
                @EmoteRelease.canceled += instance.OnEmoteRelease;
            }
        }
    }
    public HandyDandyActions @HandyDandy => new HandyDandyActions(this);
    public interface IHandyDandyActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnJumpRelease(InputAction.CallbackContext context);
        void OnEmote(InputAction.CallbackContext context);
        void OnEmoteRelease(InputAction.CallbackContext context);
    }
}
